version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    reviewers:
      - GreemDev
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 5
    reviewers:
      - GreemDev
    schedule:
      interval: weekly
